name: Ejecutar programa Python

on:
  #schedule:
  #  - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Añadir src al PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Crear carpeta config y archivo de credenciales
        run: |
          mkdir -p config
          echo "${{ secrets.GOOGLE_API_JSON }}" | base64 --decode > config/credentials.json
        
      - name: Ejecutar script principal
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          WEBHOOK_NOTIFICACIONES_ERRORES: ${{ secrets.WEBHOOK_NOTIFICACIONES_ERRORES }}
          WEBHOOK_NOTIFICACIONES_EXITOSAS: ${{ secrets.WEBHOOK_NOTIFICACIONES_EXITOSAS }}
        run: |
          python src/main.py

      - name: Notificar a Discord
        if: always()
        run: |
          STATUS="${{ job.status }}"
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"🚀 *Workflow terminado en estado:* **${STATUS}** en \`${{ github.ref_name }}\` por \`${{ github.actor }}\`\"}" \
            ${{ secrets.WEBHOOK_NOTIFICACIONES_ERRORES }}
